// <auto-generated />
namespace ePatria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Update_EM_Issue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_EM_Issue));
        
        string IMigrationMetadata.Id
        {
            get { return "201602040739150_Update_EM_Issue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
