// <auto-generated />
namespace ePatria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Update_APM_SP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_APM_SP));
        
        string IMigrationMetadata.Id
        {
            get { return "201602030418506_Update_APM_SP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
