// <auto-generated />
namespace ePatria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class APM_member : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(APM_member));
        
        string IMigrationMetadata.Id
        {
            get { return "201601150735253_APM_member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
